core/urls.py
from django.urls import include, path
from core.views import *

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    # path("<cat_title>/", category, name="category"),
    path("category/<cat_title>/", category, name="inner-category"),
    path("shop-category/<main_title>/", main_category, name="main_category"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("product/<slug:product_slug>/", product, name="product"),
    path("product/<title>/", producttitle, name="producttitle"),
    path("search/", search_view, name="search"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("checkout/", checkout_view, name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("architectures/", arch, name="arch"),
    path("architectures/<name>/", arch_name, name="arch_name"),
    path("about-us/", about, name="about-us"),
    path("contact-us/", contact, name="contact-us"),
    path("career", career, name="career"),
    path("write-to-ceo/", write_to_ceo, name="write_to_ceo"),
    path("blog/", blogs, name="blogs"),
    path("privacy-policy/", privacypolicy, name="privacypolicy"),
    path("<slug:sub_cat_slug>/", sub_category, name="sub-category"),
]

ecomproj/urls.py
from django.contrib import admin
from django.urls import path, include
from tinymce import urls as tinymce_urls
from django.contrib.sitemaps.views import sitemap
from core.sitemap import *
from core.views import RobotsTxtView
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'main_category': MainCategorySitemap,
    'category': CategorySitemap,
    'sub_category': SubCategorySitemap,
    'product': ProductSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', RobotsTxtView.as_view(), name='robots_txt'),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from core.models import *
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import Http404
import os
import requests
from django.db.models import Case, When, Value, IntegerField
from django.views.generic import View


def index(request):
    product = Main_category.objects.all()
    walpaper_cat = Company_name.objects.filter(wallpaper_category=True)
    curtain_sofa_brands = Company_name.objects.filter(curtain_sofa_brands=True)
    mattresses_brands = Company_name.objects.filter(mattresses_brands=True)
    window_blind_brands = Company_name.objects.filter(window_blinds_brands=True)
    carpet_tile_office = Company_name.objects.filter(carpet_tile_for_office_brands=True)
    rugs_brands = Company_name.objects.filter(rugs_brands=True)
    pillow_brands = Company_name.objects.filter(pillow_brands=True)
    hospital_floor_walls = Company_name.objects.filter(hospital_walls_brands=True)
    wooden_laminate = Company_name.objects.filter(wooden_laminate_flooring_brands=True)
    pvc_rubber = Company_name.objects.filter(pvc_rubber_flooring_brands=True)
    curtain_rods_channel = Company_name.objects.filter(curtains_rods_channel_brands=True)
    foam_material = Company_name.objects.filter(foam_material_brands=True)
    awning_canopy = Company_name.objects.filter(awning_canopy_brands=True)


    context = {
        "main_cat":product,
        "walpaper_cat": walpaper_cat,
        "curtain_sofa_brands": curtain_sofa_brands,
        "mattresses_brands": mattresses_brands,
        "window_blind_brands": window_blind_brands,
        "carpet_tile_office": carpet_tile_office,
        "rugs_brands": rugs_brands,
        "pillow_brands": pillow_brands,
        "hospital_floor_walls": hospital_floor_walls,
        "wooden_laminate": wooden_laminate,
        "pvcrubber": pvc_rubber,
        "curtain_rods_channel": curtain_rods_channel,
        "foam_material": foam_material,
        "awning_canopy": awning_canopy,
    }
    return render(request, 'core/index.html', context)

def category(request, cat_title):
    category = Category.objects.get(cat_title=cat_title)
    company_names = Company_name.objects.filter(category=category)
    
    # Fetch all sub-categories related to the category
    all_sub_categories = Sub_categories.objects.filter(category=category)

    # Specify the desired order for "Wallpapers" sub-categories
    wallpaper_order = ['SABYASACHI', 'Versace', 'Dolce & Gabbana', 'Lamborghini', 'Good Earth', 'Philipp Plein', 'Trussardi', 'Roberto Cavalli', 'Cole & Sons', 'Tailor Weave by Burberry', 'Customization', 'Deluxe', 'Economic']

    # Conditionally order sub-categories based on the category
    sub_categories = all_sub_categories.order_by(
        Case(
            *[When(sub_cat_title=title, then=pos) for pos, title in enumerate(wallpaper_order)],
            default=Value(999),  # Default value for other sub-categories (alphabetical order)
            output_field=IntegerField()
        )
    )

    # Fetch related products using the relationships
    products = Product.objects.filter(
        category=category,
        sub_category__in=all_sub_categories,
        company_name__in=company_names
    )

    context = {
        "category": category,
        "company_names": company_names,
        "sub_categories": sub_categories,
        "products": products,
    }

    return render(request, "core/category.html", context)


def sub_category(request, sub_cat_slug):
    sub_cats = Sub_categories.objects.filter(slug=sub_cat_slug)

    if not sub_cats.exists():
        # Handle the case where no objects are found
        raise Http404("Sub-category does not exist")

    sub_cat = sub_cats.first()

    related_sub_categories = Sub_categories.objects.filter(maincat=sub_cat.maincat, category=sub_cat.category)
    company_names = Company_name.objects.filter(sub_category=sub_cat)
    
    # Create a dictionary to store company names and their associated products
    company_products = {}
    for company in company_names:
        products = Product.objects.filter(company_name=company)
        company_products[company] = products

    # Fetch sub-categories images
    sub_cat_images = SubcategoryImages.objects.filter(sub_category=sub_cat)
    image_urls = [image.images.url for image in sub_cat_images]

    context = {
        "sub_cat": sub_cat,
        "company_products": company_products,
        "related_sub_categories": related_sub_categories,
        "sub_cat_images": sub_cat_images,
        "image_urls": image_urls,
    }

    return render(request, "core/sub-category.html", context)



def main_category(request, main_title):
    main_categories = Main_category.objects.get(main_title=main_title)
    categories = Category.objects.filter(main_category=main_categories)

    context = {
        "main_categories": main_categories,
        "categories": categories,
    }
    return render(request, "core/main_category.html", context)


def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})


def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            price_str = item['price'].replace('₹', '').replace(',', '').strip()
            price = float(price_str)
            cart_total_amount += int(item['qty']) * price

        return render(request, "core/cart.html", {"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount': cart_total_amount})
    else:
        messages.warning(request, "Your cart is empty")
        return redirect("core:index")


def product(request, product_slug):
    products = Product.objects.filter(product_slug=product_slug)

    if not products.exists():
        # Handle the case where no objects are found
        raise Http404("Product does not exist")

    # If there are multiple objects, you may want to choose one or handle the situation appropriately
    main_product = products.first()

    related_products = Product.objects.filter(company_name=main_product.company_name).exclude(pk=main_product.pk)[:10]
    product_images = ProductImages.objects.filter(product=main_product)
    product_varients = ProductVarient.objects.filter(product=main_product)
    related_company = main_product.company_name
    related_subcategory = main_product.sub_category

    context = {
        "main_product": main_product,
        "related_products": related_products,
        "product_images": product_images,
        "related_company": related_company,
        "related_subcategory": related_subcategory,
        "product_varients" : product_varients,
    }
    return render(request, "core/product.html", context)

def producttitle(request, title):
    products = Product.objects.filter(title=title)

    if not products.exists():
        # Handle the case where no objects are found
        raise Http404("Product does not exist")

    # If there are multiple objects, you may want to choose one or handle the situation appropriately
    main_product = products.first()

    related_products = Product.objects.filter(company_name=main_product.company_name).exclude(pk=main_product.pk)[:10]
    product_images = ProductImages.objects.filter(product=main_product)
    product_varients = ProductVarient.objects.filter(product=main_product)
    related_company = main_product.company_name
    related_subcategory = main_product.sub_category

    context = {
        "main_product": main_product,
        "related_products": related_products,
        "product_images": product_images,
        "related_company": related_company,
        "related_subcategory": related_subcategory,
        "product_varients" : product_varients,
    }
    return render(request, "core/product.html", context)


def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }

    return render(request, "core/search.html", context)


def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
           cart_data = request.session['cart_data_obj']
           del request.session['cart_data_obj'][product_id]
           request.session['cart_data_obj'] = cart_data

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

templates/core/contact-us.html
{% extends 'partials/base.html' %} {% load static %} 
{% block content %}
<link rel="icon" href="{% static "wp-content/themes/minimog-child-demo/assets/demos/megamog/tph.png/" %}" type="image/png">
<!-- Bootstrap CSS -->
<link href="{% static "arch/assets/css/bootstrap.min.css" %}" rel="stylesheet">
<!-- Line Awesome CSS -->
<link href="{% static "arch/assets/css/line-awesome.min.css" %}" rel="stylesheet">
<!-- Font Awesome CSS -->
<link href="{% static "arch/assets/css/fontAwesomePro.css" %}" rel="stylesheet">
<!-- Animate CSS-->
<link href="{% static "arch/assets/css/animate.css" %}" rel="stylesheet">
<!-- Bar Filler CSS -->
<link href="{% static "arch/assets/css/barfiller.css" %}" rel="stylesheet">
<!-- Magnific Popup Video -->
<link href="{% static "arch/assets/css/magnific-popup.css" %}" rel="stylesheet">
<!-- Flaticon CSS -->
<link href="{% static "arch/assets/css/flaticon.css" %} " rel="stylesheet">
<!-- Owl Carousel CSS -->
<link href="{% static "arch/assets/css/owl.carousel.css" %}" rel="stylesheet">
<!-- Slick Slider CSS -->
<link href="{% static "arch/assets/css/slick.css" %}" rel="stylesheet">
<!-- Nice Select  -->
<link href="{% static "arch/assets/css/nice-select.css" %}" rel="stylesheet">
<!-- Back to Top -->
<link href="{% static "arch/assets/css/backToTop.css" %}" rel="stylesheet">
<!-- Metis Menu -->
<link href="{% static "arch/assets/css/metismenu.css" %}" rel="stylesheet">
<!-- Style CSS -->
<link href="{% static "arch/assets/css/style.css" %}" rel="stylesheet">
<!-- Responsive CSS -->
<link href="{% static "arch/assets/css/responsive.css" %}" rel="stylesheet">


<!-- jquery -->
<script src="{% static "arch/assets/js/jquery-1.12.4.min.js" %}"></script>
<div class="contact-page section-padding">
    <div class="container">
        <div class="row gx-5">
            <div class="col-xl-6 col-lg-6 col-12">
                <div class="contact-page google-map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.018290064745!2d77.22094837503133!3d28.56921348695409!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d00e5a6e640ad%3A0xab0c231085c5e591!2sPanipat%20Handloom%20Emporium%20-%20Wooden%20Flooring%20%7C%20Wallpaper%20%7C%20Windows%20Blinds%20%7C%20Mattress%20%7C%20Interior%20%26%20Exterior%20Shop%20%7C%20Sofa%20Cloth!5e0!3m2!1sen!2sin!4v1700566835093!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-12">
                <div class="contact-form">
                    <div class="section-title">
                        <h2>Lets talk...</h2>                            
                    </div>
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Your Name*</label>
                                <input type="text" placeholder="Your Full Name">
                            </div>
                            <div class="col-md-6">
                                <label>Email Address*</label>
                                <input type="email" placeholder="E-mail Address">
                            </div>
                            <div class="col-12">
                                <label>Subject*</label>
                                <input type="text" placeholder="Website">
                            </div>
                            <div class="col-12">
                                <label>Message*</label>
                                <textarea name="message" id="message" cols="30" rows="10" placeholder="Write Here"></textarea>
                            </div>
                            <div><button type="submit" class="bordered-btn">Send Now</button></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Contact Info -->
<div class="contact-info-wrap section-padding pt-0 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-4 col-md-6 col-12">
                <div class="single-contact-info">
                    <div class="contact-icon">
                        <img src="{% static "arch/assets/img/contact/1.png" %}" alt="">
                    </div>
                    <p>N-14, South Extn-1, Gurudwara Road, New Delhi-110049</p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-6 col-12">
                <div class="single-contact-info">
                    <div class="contact-icon">
                        <img src="{% static "arch/assets/img/contact/2.png" %}" alt="">
                    </div>
                    <p>Team@thepanipathandloom.com</p>
                    <p>Accounts@thepanipathandloom.com</p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-6 col-12">
                <div class="single-contact-info">
                    <div class="contact-icon">
                        <img src="{% static "arch/assets/img/contact/3.png" %}" alt="">
                    </div>
                    <p>+91-9999999009</p>
                    <p>+91-9899073000</p>
                    <p>011-24622572</p>
                    <p>011-24610143</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/core/main_category.html
{% extends 'partials/base.html' %}
{% load static %}
{% block breadmb %}
<div id="page-title-bar" class="page-title-bar page-title-bar-minimal-01">
  <div class="page-title-bar-inner">
    <div class="page-title-bar-bg"></div>

    <div id="page-breadcrumb" class="page-breadcrumb">
      <div class="container-broad">
        <div class="page-breadcrumb-wrap">
          <ul class="insight_core_breadcrumb">
            <li class="level-1 top item-home">
              <a href="/">Home</a>
            </li>
            <li class="level-2 sub item-current tail current">
                <span>{{main_categories.main_title}}</span>
              </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock breadmb %} 

{% block content %}
<div id="page-content" class="page-content">
  <div class="container-broad">
    <div class="row">
      <div class="page-sidebar page-sidebar-left sidebar-primary">
        <div
          class="page-sidebar-inner tm-sticky-column"
          data-sticky-group="content-sidebar"
          itemscope="itemscope"
        >
          <a href="#" class="btn-close-off-sidebar">
            <svg
              width="18"
              height="18"
              viewBox="0 0 18 18"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M10.6465 8.975L16.7012 15.0297C16.8639 15.1924 16.8639 15.3715 16.7012 15.5668L15.5781 16.6898C15.3828 16.8526 15.2038 16.8526 15.041 16.6898L14.0156 15.6156L8.98633 10.6352L2.93164 16.6898C2.76888 16.8526 2.58984 16.8526 2.39453 16.6898L1.27148 15.5668C1.10872 15.3715 1.10872 15.1924 1.27148 15.0297L7.32617 8.975L1.27148 2.92031C1.10872 2.75755 1.10872 2.57852 1.27148 2.3832L2.39453 1.26016C2.58984 1.0974 2.76888 1.0974 2.93164 1.26016L8.98633 7.31484L15.041 1.26016C15.2038 1.0974 15.3828 1.0974 15.5781 1.26016L16.7012 2.3832C16.8639 2.57852 16.8639 2.75755 16.7012 2.92031L15.627 3.9457L10.6465 8.975Z"
                fill="#000000"
              />
            </svg>
          </a>
          <div class="page-sidebar-content-wrap">
            <div class="page-sidebar-content"></div>
          </div>
        </div>
      </div>

      <div class="page-main-content">
        <div id="dokan-store-tabs-wrap" class="dokan-store-tabs-wrap"></div>

        <div class="dokan-store-wrap layout-left">
          <div id="dokan-primary" class="dokan-single-store">
            <div
              id="dokan-content"
              class="store-page-wrap woocommerce"
              role="main"
            >
              <div class="seller-items">
                <div
                  id="minimog-main-post"
                  class="minimog-main-post minimog-grid-wrapper minimog-product group-style-06 style-grid-06 caption-style-06"
                  data-grid='{"type":"grid","columns":"4","columnsTabletExtra":"3","columnsMobileExtra":"2","gutter":"30","gutterTabletExtra":"20","gutterMobileExtra":"16"}'
                  style="
                    --grid-columns-desktop: 4;
                    --grid-columns-tablet-extra: 3;
                    --grid-columns-mobile-extra: 2;
                    --grid-gutter-desktop: 30;
                    --grid-gutter-tablet-extra: 20;
                    --grid-gutter-mobile-extra: 16;
                  "
                >
                  <div class="minimog-grid lazy-grid">
                    <div class="grid-sizer"></div>
                   {% for main in categories %}
                    <div
                      class="grid-item product type-product post-987 status-publish instock product_cat-dishwashers product_tag-dishwasher has-post-thumbnail shipping-taxable purchasable product-type-variable has-default-attributes vi-sctv-product"
                    >
                      <div class="product-wrapper">
                        <div class="product-thumbnail">
                          <div class="thumbnail">
                            <a
                              href="{% url 'core:inner-category' main.cat_title %}"
                              class="woocommerce-LoopProduct-link woocommerce-loop-product__link"
                            >
                              <div class="product-main-image">
                                <div
                                  class="minimog-lazy-image"
                                  style="
                                    --lazy-image-width: 450px;
                                    --lazy-image-height: 100%;
                                  "
                                >
                                  <img
                                    src="data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%22http://www.w3.org/2000/svg%22%20viewBox%3D%220%200%20450%20450%22%3E%3C%2Fsvg%3E"
                                    width="450"
                                    height="450"
                                    alt=""
                                    data-src="{{main.image.url}}"
                                    class="product-main-image-img ll-image"
                                  />
                                </div>
                              </div>

                              <div class="product-hover-image">
                                <div
                                  class="minimog-lazy-image"
                                  style="
                                    --lazy-image-width: 450px;
                                    --lazy-image-height: 100%;
                                  "
                                >
                                  <img
                                    src="data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%22http://www.w3.org/2000/svg%22%20viewBox%3D%220%200%20450%20450%22%3E%3C%2Fsvg%3E"
                                    width="450"
                                    height="450"
                                    alt="product_kitchen_2_3"
                                    data-src=""
                                    class="ll-image"
                                  />
                                </div>
                              </div>
                            </a>
                          </div>
                        </div>

                        <div class="product-info">
                          <div class="loop-product-category">
                            <a
                              href=""
                            >
                            {{main_categories.main_title}}
                            </a>
                          </div>

                          <h3
                            class="woocommerce-loop-product__title post-title-2-rows"
                          >
                            <a
                              href="{% url 'core:inner-category' main.cat_title %}"
                              >  {{main.cat_title}}</a
                            >
                          </h3>

                          

                       

                          <div class="content-view-list">
                            <div
                              class="woocommerce-loop-product__desc post-title-2-rows"
                            >
                             
                            </div>

                            <div class="product-list-view-actions">
                              <div
                                class="product-action hint--bounce hint--top woocommerce_loop_add_to_cart_wrap"
                                data-hint="Select options"
                              >
                                <a
                                  href="{% url 'core:inner-category' main.cat_title %}"
                                  data-quantity="1"
                                  class="button wp-element-button product_type_variable add_to_cart_button"
                                  data-product_id="987"
                                  data-product_sku=""
                                  aria-label="Select options for &ldquo;Built-in dishwasher, Stainless steel Essentiell&rdquo;"
                                  rel="nofollow"
                                  ><span>View Products</span></a
                                >
                              </div>
                              <div
                                class="product-action wishlist-btn style-01 icon-star hint--bounce hint--top"
                                data-hint="Add to wishlist"
                              >
                                <a
                                  href="?add-to-wishlist=987"
                                  class="woosw-btn woosw-btn-987"
                                  data-id="987"
                                  data-product_name="Built-in dishwasher, Stainless steel Essentiell"
                                  data-product_image=""
                                  >Add to wishlist</a
                                >
                              </div>
                              <div
                                class="product-action compare-btn style-01 hint--bounce hint--top"
                                data-hint="Compare"
                              >
                                <a
                                  href="?add-to-compare=987"
                                  class="woosc-btn woosc-btn-987"
                                  data-id="987"
                                  data-product_name="Built-in dishwasher, Stainless steel Essentiell"
                                  data-product_image=""
                                  >Compare</a
                                >
                              </div>
                              <div
                                class="product-action quick-view-btn style-01 hint--bounce hint--top"
                                data-hint="Quick view"
                                data-pid="987"
                              >
                                <a class="quick-view-icon" href="#"
                                  >Quick view</a
                                >
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="background-color-expand">
                        <div
                          class="product-action hint--bounce hint--top woocommerce_loop_add_to_cart_wrap"
                          data-hint="Select options"
                        >
                          <a
                            href="{% url 'core:inner-category' main.cat_title %}"
                            data-quantity="1"
                            class="button wp-element-button product_type_variable add_to_cart_button"
                            data-product_id="987"
                            data-product_sku=""
                            aria-label="Select options for &ldquo;Built-in dishwasher, Stainless steel Essentiell&rdquo;"
                            rel="nofollow"
                            ><span>View Products</span></a
                          >
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                 



                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- .dokan-single-store -->
        </div>
        <!-- .dokan-store-wrap -->
      </div>
    </div>
  </div>
</div>
{% endblock content %}